- hosts: all
  become: yes
  gather_facts: true
  become_user: root

  vars:
    ntp_server1: ntp1.stratum1.ru
    ntp_server2: ntp2.stratum1.ru
    ntp_server3: ntp3.stratum1.ru
    ntp_server4: ntp4.stratum1.ru

  tasks:
    - name: Distribution
      debug: msg="{{ ansible_os_family }}"

    - name: deploy ntp.conf to Debian hosts
      include_tasks: templates/debian.yml
      when: ansible_os_family == 'Debian'
      tags: package

    - name: deploy ntp.conf to Redhat hosts
      include_tasks: templates/redhat.yml
      when: ansible_os_family == 'RedHat'
      tags: package